/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/common/Dialog.vue')['default']
    Empty: typeof import('./src/components/common/Empty.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    ModalPlace: typeof import('./src/components/common/ModalPlace.vue')['default']
    ModalStore: typeof import('./src/components/common/ModalStore.vue')['default']
    ModalUser: typeof import('./src/components/common/ModalUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/common/TabBar.vue')['default']
    TopNavBar: typeof import('./src/components/common/TopNavBar.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
