-- 为 pets 表添加新字段
USE pet_community;

-- 添加新字段
ALTER TABLE pets 
ADD COLUMN IF NOT EXISTS gender VARCHAR(10) COMMENT '性别',
ADD COLUMN IF NOT EXISTS color VARCHAR(50) COMMENT '毛色',
ADD COLUMN IF NOT EXISTS weight DECIMAL(5,2) COMMENT '体重(kg)',
ADD COLUMN IF NOT EXISTS size VARCHAR(20) COMMENT '体型',
ADD COLUMN IF NOT EXISTS neutered TINYINT(1) DEFAULT 0 COMMENT '是否绝育',
ADD COLUMN IF NOT EXISTS vaccinated VARCHAR(20) COMMENT '疫苗接种情况',
ADD COLUMN IF NOT EXISTS health_certificate TINYINT(1) DEFAULT 0 COMMENT '是否有健康证明',
ADD COLUMN IF NOT EXISTS personality VARCHAR(200) COMMENT '性格特点',
ADD COLUMN IF NOT EXISTS habits TEXT COMMENT '特殊习惯',
ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- 添加索引（如果需要）
ALTER TABLE pets ADD INDEX IF NOT EXISTS idx_pets_user_id (user_id);

SELECT 'Migration completed successfully' AS result;